### ISSUE TITLE
Event Detection Helper Audio Loader

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/ap-desktop#18]
System returns error: net::ERR_REQUEST_RANGE_NOT_SATISFIABLE when event detection helper is run on events which do not include the temporary .wav files. This should instead alert users to change their config files to turn these on instead.

**Comment by atruskie** [comment]
I'll need more information to diagnose this. Please attach at least a log.

**Comment by Allcharles** [comment]
Just a reminder for myself, the error is caused when the intermediaste .wav file does not exist. All I need to do to fix the error is determine whether the file exists before reading it. If you want to see where the bug is, its caused by `fs.readFile(eventCurrent.sound, function(err, buffer) {` line 259 of utilities.js.

**Comment by atruskie** [comment]
Ah sorry my bad. Should have read better.
