### ISSUE TITLE
Application slow down processing big data

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/ap-desktop#23]
Collection system parts which slow down the system when processing large amounts of data:
- [ ] Running analysis with --log-level=7 spams the pre tag lagging out the system
- [ ] Giving large number of files causes lag when building output page

This issue will expand overtime as I find areas for improvement.

**Comment by atruskie** [comment]
I'd suggest windowing the output log. If log > 1000 lines, only show last 1000 lines, provide link/path to full log.
