### ISSUE TITLE
Event Detector Utility Sound Player

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/ap-desktop#3]
On some systems the sound player does not output any sound. This is likely because the audio does not output to all audio channels. An example of something similar on windows is to open speaker properties, under advanced there is a test audio file. Some speakers cannot play this file in its entirety and thus no sound is played for parts.
This is a very specific edge case that applied to my PC.

**Comment by atruskie** [comment]
All audio output by AP.exe is a mono mixdown of the input audio. 

If this issue is truly isolated to your PC then I'd suggest the issue doesn't belong in this bug tracker
