### ISSUE TITLE
Production

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/ap-desktop#4]
HTML elements fail to load images and sound files when given full file paths instead of relative file paths. This issue only affects production and not the development code.

**Comment by atruskie** [comment]
@Allcharles please cross-link commits with issues https://help.github.com/en/articles/closing-issues-using-keywords

Please add/edit this thread to include the commit hash where this was fixed

**Comment by Allcharles** [comment]
Fixed in commit 942daa01933aa9c14e2bb99fdfebe14175aee93e
