### ISSUE TITLE
Output Folder

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/ap-desktop#9]
## Environment
Linux Mint 18.3
Windows 10

## Bug
When selecting output folder, if cancel button is pressed the header becomes red. This does not affect the ability to submit an analysis.

## Expected Outcome
Output folder header should never turn red unless in future we detect if the folder does not allow for write permission.

**Comment by atruskie** [comment]
@Allcharles please cross-link commits with issues https://help.github.com/en/articles/closing-issues-using-keywords

Please add/edit this thread to include the commit hash where this was fixed
